---
- name: Prepare directories
  file:
    path: "/tmp/app-agent"
    state: directory

- name: Download reusable binaries locally
  get_url:
    url: "https://github.com/QingCloudAppcenter/AppcenterAgent/releases/download/{{ appAgentVersion }}/app-agent-linux-amd64.tar.gz"
    dest: "files/tmp/app-agent-{{ appAgentVersion }}.tgz"
  delegate_to: localhost

- name: Extract binary
  unarchive:
    src: "files/tmp/app-agent-{{ appAgentVersion }}.tgz"
    dest: "/tmp/app-agent"
    creates: "/tmp/app-agent/bin"
    extra_opts: [ --strip-components=1 ]

- name: Create symbolic Link
  raw: |
    cd /tmp/app-agent
    ./install.sh

