[template]
src = "elasticsearch-exporter.sh.tmpl"
dest = "/opt/app/bin/tmpl/elasticsearch-exporter.sh"
mode = "0700"
keys = [
  "/",
]
reload_cmd = "/opt/app/bin/tmpl/elasticsearch-exporter.sh; appctl reload elasticsearch-exporter"
