---
- name: setting facts - LS plugins
  set_fact:
    ls_home: /opt/logstash/current
    local_dir: files/tmp/ls-plugins
    remote_dir: /opt/logstash/current/plugins

- name: Check if the plugin was installed - {{ opts.name }}
  command: "grep -q {{ opts.name }} {{ ls_home }}/Gemfile"
  register: installed
  ignore_errors: True

- name: Prepare LS plugins directory
  file:
    dest: "{{ remote_dir }}"
    owner: logstash
    group: svc
    state: directory

- name: Prepare local tmp dir for LS plugins
  file:
    dest: "{{ local_dir }}"
    state: directory
  delegate_to: localhost

- name: Download LS plugin - {{ opts.name }}
  get_url:
    url: "{{ opts.url | default('https://github.com/logstash-plugins/{{ opts.name }}/archive/v{{ opts.version }}.zip') }}"
    dest: "{{ local_dir }}/{{ opts.name }}-{{ opts.version }}.zip"
  delegate_to: localhost
  when: installed is failed

- name: Extract LS plugin - {{ opts.name }}
  unarchive:
    src: "{{ local_dir }}/{{ opts.name }}-{{ opts.version }}.zip"
    dest: "{{ remote_dir }}"
    creates: "{{ remote_dir }}/{{ opts.name }}-{{ opts.version }}"
    owner: logstash
    group: svc
  when: installed is failed

- name: Add to Gemfile
  lineinfile:
    path: "{{ ls_home }}/Gemfile"
    regexp: '^gem "{{ opts.name }}"'
    line: 'gem "{{ opts.name }}", :path => "./plugins/{{ opts.name }}-{{ opts.version }}"'

- name: Install LS plugin - {{ opts.name }}
  shell: "{{ ls_home }}/bin/logstash-plugin install --no-verify"
  args:
    chdir: "{{ ls_home }}"
  become: yes
  become_user: root
  when: installed is failed
